PUT http://localhost:8080/api/planes/3 HTTP/1.1
Content-Type: application/json

{
    "idPlan": 3,
    "nombrePlan": "Zumba",
    "precio": 1600
}

###

GET http://localhost:8080/api/planes HTTP/1.1
Content-Type: application/json

###

DELETE http://localhost:8080/api/planes/3 HTTP/1.1
Content-Type: application/json